language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in secring.gpg.enc -out secring.gpg
  -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in pubring.gpg.enc -out pubring.gpg
  -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in gradle.properties.enc -out
  gradle.properties -d
- rvm install 2.0.0
- gem install travis-custom-deploy
addons:
  sonarqube: true
install: /bin/true
sudo: false
script:
- TERM=dumb gradle clean deploy uploadArchives
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
after_success: 
- curl -L $JENKINS_URL
- travis-custom-deploy sftp bparser/build/jacocoHtml
env:
  global:
  - secure: laGlF46pirAFs3xrBTm+7AFi0CubtBj0PRLqhAe2q9wEhyUvU+LOhJZiqeyuc2FBzGOSlfevGhVOgmWxph6g2EP/bxhwiFywXD/CCzjDhca2JahMdYW925006jGIfh+QmWnxb7hoXUb+DvOoDQdHoiTPmVom2oTEGTctjLB4BhI=
  - secure: tWYKjEfXvz2c4sYc6UjsaZBy0PwSBgle4U67C6IkfI1ps64yyi9f7Aj2vLqo2prXSWOOg4FF2o13BdqjqSk0H/4+WprxEKTjqLHc09F+G5/31XbhEqvL9rZ2mWAktNnFKS+dQQ+p7n0askM/hNfZYYpBra7Sz4IWP7qM2igTZgQ=
  - secure: wgmLBvs07wusTkYE45CvFKZ3Wnvft9AmwMaQm3cQxtdWY3MX53Eocecs/0uwUkhtdw7kBnwxCh6RsbLnEQinDTzKS3hsbm4GaLFzuRhaPQ9AirqPisifMXE9fUfj+AAfgwscWlMgUdNgUvUCXiRV6Y4m3hIqZSsBSavrR9Lh3GA=
  - secure: GxGGpIcdDUyqpLNL6QeRjggqHBUSfsSVTijvDPfLk1dxSnzOoiqJdLskCr7S5EwETaeTfJPAFNj03IIolWxXKdspz8H6itarF5ASCaH8GbHcszJe72EgC7OxvYgnAqKk0g6aaTgRVqgJ9QhaapT3o4pd2FwKuYTKXlU7JLxmsj4=
  - secure: OYrz+2ziI4SXqr64R1e7XvhxwR6LoC1S7HT4uXNfNytfEuKA7t8hqKBkCDMFeyn9yb0r/YUHT6qT+7vvbr+x85/sNOUe5fKZQfLogrUk3OCS/AHKuYC03/zZU06GrRh4US3WaicQOD9gleHdPNyhLjVuAF8pAp73lnhrK3RY27s=
  - secure: bpeR8mW7A77c1G4AuUJ6jV0pA/IDzOtUpbJODN2Kv1paZAZQVIqQ6pbAu6EtPVBOTw9665pUNFGHIQjDi8o5GfZcHMbxIoN1xtvw/LR04bqYEiLZiukC6439lsWLj8wOidgTVTk4fP31uMCEzaarhUm/OPjgxEBoVlNXl603d48=
  - secure: jjgHqVcIhsp8D/4o94BdM4F4MXBH9Iur05JmW3VK7KVeKyYAHuS8KQWIa5aCbGXKwXL+SPKY10Keb+DLDX96FqdxXjWNaS//zQ9vdCTheKk5lcx2O6ONa8A/Bl3cSJb2KrvaJb7KWiSjN8V9UQk8hP8lhklYVclCPNVFA63gSPQ=
  - secure: m0ZOt3vPvdqdQ4uEh2osifeyqdd+QQ4aVoAL0OrHziEHZW210mKC6QtZASPL1ZjiwpRuEIyWToaMfFG8K4vscQ4y2XVO4xSiSLyLGP7fyn+kqotQhXsk9yeaqvbiboese11VtpaTk32jDcm4HsSb/hKnWqGW/AbQDoxHk6pjPpE=
notifications:
  slack:
    secure: aCJrcizSAsjZDb7l3kOvZThwy2vufeuoWfSWIGLUK1hWGx0+DnRY5fVx+eeHni+2WVyv1sXYaJiNcfJVsdWIGhQ5dge8Sw9fy+vanCAXgRyxnMG4Hj644+T9hBSfHE41QsQZev7sL/YCvL9qBQhxLG92JZOtMG8M9iYG0An7RU8=
