language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in secring.gpg.enc -out secring.gpg
  -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in pubring.gpg.enc -out pubring.gpg
  -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in gradle.properties.enc -out
  gradle.properties -d
addons:
  sonarcloud:
    branches:
     - master
     - develop

install: /bin/true
sudo: false

script:
  - TERM=dumb ./gradlew clean deploy uploadArchives
after_success:
  - curl -L $JENKINS_URL
  - TERM=dumb ./gradlew sonarqube --info --stacktrace
env:
  global:
  - secure: laGlF46pirAFs3xrBTm+7AFi0CubtBj0PRLqhAe2q9wEhyUvU+LOhJZiqeyuc2FBzGOSlfevGhVOgmWxph6g2EP/bxhwiFywXD/CCzjDhca2JahMdYW925006jGIfh+QmWnxb7hoXUb+DvOoDQdHoiTPmVom2oTEGTctjLB4BhI=
  - secure: tWYKjEfXvz2c4sYc6UjsaZBy0PwSBgle4U67C6IkfI1ps64yyi9f7Aj2vLqo2prXSWOOg4FF2o13BdqjqSk0H/4+WprxEKTjqLHc09F+G5/31XbhEqvL9rZ2mWAktNnFKS+dQQ+p7n0askM/hNfZYYpBra7Sz4IWP7qM2igTZgQ=
  - secure: wgmLBvs07wusTkYE45CvFKZ3Wnvft9AmwMaQm3cQxtdWY3MX53Eocecs/0uwUkhtdw7kBnwxCh6RsbLnEQinDTzKS3hsbm4GaLFzuRhaPQ9AirqPisifMXE9fUfj+AAfgwscWlMgUdNgUvUCXiRV6Y4m3hIqZSsBSavrR9Lh3GA=
notifications:
  slack:
    secure: aCJrcizSAsjZDb7l3kOvZThwy2vufeuoWfSWIGLUK1hWGx0+DnRY5fVx+eeHni+2WVyv1sXYaJiNcfJVsdWIGhQ5dge8Sw9fy+vanCAXgRyxnMG4Hj644+T9hBSfHE41QsQZev7sL/YCvL9qBQhxLG92JZOtMG8M9iYG0An7RU8=
